#!/usr/bin/env bash
# This is what mission 12 schedules with `at`. It does not exist as
# evidence until it actually runs — that's the whole point of the mission.
set -u
SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
source "$SCRIPT_DIR/lib/common.sh"
source "$SCRIPT_DIR/lib/flaglib.sh"
ensure_workspace
out="$LAB_WORKSPACE/rooms/12/evidence.txt"
mkdir -p "$(dirname "$out")"
{
    printf 'Evidence generated by a one-time scheduled job at: %s\n' "$(date)"
    gen_flag 12 delayed_evidence
} > "$out"
